# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: database.yml }

framework:
    default_locale: %sylius.locale%
    form: ~
    charset:       UTF-8
    secret: %sylius.secret%
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing/base.yml" }
    validation:    { enabled: true }
    translator:    { fallback: %sylius.locale% }
    templating:    { engines: ['twig', 'php'] }
    session:
        name: SYLIUS_SANDBOX_SESSION
        lifetime: 72000
        auto_start:     true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug% 
    
swiftmailer:
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%

sylius_assortment:
    driver: ORM
    classes:
        model:
            product:  Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Product
        form:
            type:
                product: Sylius\Sandbox\Bundle\AssortmentBundle\Form\Type\ProductFormType

sylius_catalog:
    driver: ORM
    catalogs:
        assortment:
            mode: S
            property: "products"
            sorter: sylius_assortment.sorter.product
            classes:
                model: Sylius\Sandbox\Bundle\AssortmentBundle\Entity\Category
            templates:
                backend:
                    list: SandboxAssortmentBundle:Backend/Category:list.html.twig
                    show: SandboxAssortmentBundle:Backend/Category:show.html.twig
                    create: SandboxAssortmentBundle:Backend/Category:create.html.twig
                    update: SandboxAssortmentBundle:Backend/Category:update.html.twig
                frontend:
                    list: SandboxAssortmentBundle:Frontend/Category:list.html.twig
                    show: SandboxAssortmentBundle:Frontend/Category:show.html.twig
                    
sylius_cart:
    driver: ORM
    engine: twig
    operator: sylius_core.cart.operator
    classes:
        model:
            cart: Sylius\Sandbox\Bundle\CartBundle\Entity\Cart
            item: Sylius\Sandbox\Bundle\CartBundle\Entity\Item
        form:
           type:
               item: Sylius\Sandbox\Bundle\CartBundle\Form\Type\ItemType

liip_theme:
        themes: ~
        active_theme: ~
                            
sylius_theming:
    driver: ORM
    classes:
        model:
            theme: Sylius\Bundle\ThemingBundle\Entity\Theme
                
sylius_sales:
    driver: ORM
    statuses:
        - "status.0"
        - "status.1"
        - "status.2"
    classes:
        model:
            order: Sylius\Sandbox\Bundle\SalesBundle\Entity\Order
        form:
            type:
                order: Sylius\Sandbox\Bundle\SalesBundle\Form\Type\OrderFormType
                
sylius_plugins:
    driver: ORM
    classes:
        model:
            plugin: Sylius\Bundle\PluginsBundle\Entity\Plugin
