# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

framework:
    default_locale: en
    form: ~
    charset:       UTF-8
    secret: eXdedaw24XU
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing/installation.yml" }
    validation:    { enabled: true }
    translator:    { fallback: en }
    templating:    { engines: ['twig', 'php'] }
    session:
        name: SYLIUS_SESSION
        lifetime: 72000
        auto_start:     true

twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    
sylius_installer: ~
