# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: base.yml }

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: error
    