# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        sylius_guard_provider:
            chain:
                providers: [sylius_guard_provider.memory, sylius_guard_provider.database]
        sylius_guard_provider.memory:
            memory:
                users:
                    %sylius.security.login%:  { password: %syilus.security.password %, roles: 'ROLE_SYLIUS_ADMIN' }
        sylius_guard_provider.database:
            id: sylius_guard.security.provider
    encoders:
        Sylius\Bundle\CoreBundle\Entity\User:
            id: sylius_guard.security.encoder
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
    firewalls:
        main:
            form_login:
                provider: sylius_guard_provider
                login_path: /login
                check_path: /login
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: SYLIUS_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout: true
            anonymous: true
    access_control:
        - { path: "/administration.*", role: ROLE_SYLIUS_ADMIN }
